version: 2.1

jobs:
  build:
    docker:
      - image: docker:19.03.12
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t myapp .
      - run:
          name: Test Docker container
          command: |
            docker run -d -p 8080:8080 --name myapp_container myapp
            sleep 5
            apt install curl
            curl -sSf http://localhost:8080
            docker stop myapp_container
            docker rm myapp_container