version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt update
            sudo apt install -y nodejs npm wget
      - run:
          name: Build and test
          command: |
            npm install
            npm test
      - run:
          name: Test wget
          command: |
            wget http://localhost:8080
