version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: medium

    steps:
      - checkout

      - run:
          name: Build And Run Docker
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t iwarzie/nodejs_sample:$TAG .
            docker run --rm -d -p 8080:8080 --name backspace iwarzie/nodejs_sample:$TAG
            sleep 3
            curl http://localhost:8080
            docker stop backspace
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push iwarzie/nodejs_sample:$TAG

workflows:
  build-docker-workflow:
    jobs:
      - build